package generate

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/storacha/smelt/pkg/manifest"
	"gopkg.in/yaml.v3"
)

const composeHeader = "# Auto-generated by smelt -- DO NOT EDIT\n# Re-generate with: smelt generate (or make generate)\n"

// GeneratePiriCompose generates the piri system Docker Compose YAML for N piri nodes.
func GeneratePiriCompose(nodes []manifest.ResolvedPiriNode) ([]byte, error) {
	compose := newComposeFile()

	needsPostgres := false
	needsS3 := false
	var postgresDBs []string

	for _, node := range nodes {
		svc := buildPiriService(node)
		compose.Services[node.Name] = svc

		// Serialize startup: each piri-N waits for piri-(N-1) to be healthy before
		// starting its own init. Avoids a thundering-herd race where concurrent
		// gas estimation against a shared pending state underestimates gas for the
		// loser and its createDataSet tx reverts out-of-gas. See storacha/piri#466.
		if node.Index > 0 {
			svc.DependsOn[fmt.Sprintf("piri-%d", node.Index-1)] = DependsOnCondition{Condition: "service_healthy"}
		}

		if node.Storage.DB == manifest.DBPostgres {
			needsPostgres = true
			postgresDBs = append(postgresDBs, fmt.Sprintf("piri_%d", node.Index))

			// Add infra dependencies to this node.
			svc.DependsOn["piri-postgres-init"] = DependsOnCondition{Condition: "service_completed_successfully"}
		}
		if node.Storage.Blob == manifest.BlobS3 {
			needsS3 = true
			svc.DependsOn["piri-minio"] = DependsOnCondition{Condition: "service_healthy"}
		}
		if node.Storage.DB == manifest.DBPostgres || node.Storage.Blob == manifest.BlobS3 {
			svc.Networks = append(svc.Networks, "piri-storage-net")
		}

		compose.Services[node.Name] = svc
		compose.Volumes[fmt.Sprintf("%s-data", node.Name)] = nil
	}

	if needsPostgres {
		compose.Services["piri-postgres"] = buildPostgresService()
		compose.Services["piri-postgres-init"] = buildPostgresInitService(postgresDBs)
		compose.Volumes["piri-postgres-data"] = nil
	}
	if needsS3 {
		compose.Services["piri-minio"] = buildMinioService()
		compose.Volumes["piri-minio-data"] = nil
	}
	if needsPostgres || needsS3 {
		compose.Networks["piri-storage-net"] = nil
	}

	return marshalCompose(compose)
}

func buildPiriService(node manifest.ResolvedPiriNode) ComposeService {
	image := "${PIRI_IMAGE:-ghcr.io/storacha/piri:main}"
	if node.Image != "" {
		image = node.Image
	}

	env := []string{
		"DYNAMODB_ENDPOINT=http://dynamodb-local:8000",
		"DYNAMODB_TABLE=delegator-allow-list",
		"OPERATOR_EMAIL=local@test.com",
		"PIRI_UCAN_INSECURE_DID_RESOLUTION=true",
		fmt.Sprintf("PUBLIC_URL=http://%s:3000", node.Name),
		fmt.Sprintf("PIRI_DB_BACKEND=%s", node.Storage.DB),
		fmt.Sprintf("PIRI_BLOB_BACKEND=%s", node.Storage.Blob),
	}

	if node.Storage.DB == manifest.DBPostgres {
		env = append(env,
			fmt.Sprintf("PIRI_DB_POSTGRES_URL=postgres://piri:piri@piri-postgres:5432/piri_%d?sslmode=disable", node.Index),
		)
	}
	if node.Storage.Blob == manifest.BlobS3 {
		env = append(env,
			"PIRI_S3_ENDPOINT=piri-minio:9000",
			fmt.Sprintf("PIRI_S3_BUCKET_PREFIX=%s-", node.Name),
			"PIRI_S3_ACCESS_KEY_ID=minioadmin",
			"PIRI_S3_SECRET_ACCESS_KEY=minioadmin",
			"PIRI_S3_INSECURE=true",
		)
	}

	return ComposeService{
		Image:      image,
		User:       "0:0",
		Ports:      []string{fmt.Sprintf("%d:3000", 4000+node.Index)},
		Entrypoint: []string{"/entrypoint.sh"},
		Volumes: []string{
			fmt.Sprintf("%s-data:/data/piri", node.Name),
			fmt.Sprintf("../keys/%s.pem:/keys/piri.pem:ro", node.Name),
			fmt.Sprintf("../keys/%s-wallet.hex:/keys/owner-wallet.hex:ro", node.Name),
			"../../systems/piri/entrypoint.sh:/entrypoint.sh:ro",
			"../../systems/piri/register-did.sh:/scripts/register-did.sh:ro",
			"../../systems/piri/config/piri-base-config.toml:/config/piri-base-config.toml:ro",
			"../../systems/piri/config/piri-overrides.toml:/config/piri-overrides.toml:ro",
		},
		Environment: env,
		DependsOn: map[string]DependsOnCondition{
			"blockchain":      {Condition: "service_healthy"},
			"indexer":         {Condition: "service_healthy"},
			"signing-service": {Condition: "service_healthy"},
			"delegator":       {Condition: "service_healthy"},
			"dynamodb-local":  {Condition: "service_healthy"},
			"upload":          {Condition: "service_healthy"},
		},
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3000/readyz"},
			Interval:    "10s",
			Timeout:     "5s",
			Retries:     30,
			StartPeriod: "180s",
		},
		Restart:  "unless-stopped",
		Networks: []string{"storacha-network"},
	}
}

func buildPostgresService() ComposeService {
	return ComposeService{
		Image: "postgres:16-alpine",
		Ports: []string{"5432:5432"},
		Environment: []string{
			"POSTGRES_USER=piri",
			"POSTGRES_PASSWORD=piri",
			"POSTGRES_DB=postgres",
		},
		Volumes: []string{
			"piri-postgres-data:/var/lib/postgresql/data",
		},
		Healthcheck: &Healthcheck{
			Test:     []string{"CMD-SHELL", "pg_isready -U piri -d postgres"},
			Interval: "5s",
			Timeout:  "3s",
			Retries:  10,
		},
		Restart:  "unless-stopped",
		Networks: []string{"piri-storage-net"},
	}
}

func buildPostgresInitService(databases []string) ComposeService {
	// Build idempotent CREATE DATABASE commands.
	var cmds []string
	for _, db := range databases {
		cmds = append(cmds,
			fmt.Sprintf(`psql -h piri-postgres -U piri -d postgres -tc "SELECT 1 FROM pg_database WHERE datname = '%s'" | grep -q 1 || psql -h piri-postgres -U piri -d postgres -c "CREATE DATABASE %s;"`, db, db),
		)
	}
	script := strings.Join(cmds, "\n")

	return ComposeService{
		Image:      "postgres:16-alpine",
		Entrypoint: []string{"sh", "-c"},
		Command:    []string{script},
		Environment: []string{
			"PGPASSWORD=piri",
		},
		DependsOn: map[string]DependsOnCondition{
			"piri-postgres": {Condition: "service_healthy"},
		},
		Restart:  "no",
		Networks: []string{"piri-storage-net"},
	}
}

func buildMinioService() ComposeService {
	return ComposeService{
		Image:   "minio/minio:latest",
		Command: []string{"server", "/data", "--console-address", ":9001"},
		Ports:   []string{"9002:9000", "9003:9001"},
		Environment: []string{
			"MINIO_ROOT_USER=minioadmin",
			"MINIO_ROOT_PASSWORD=minioadmin",
		},
		Volumes: []string{
			"piri-minio-data:/data",
		},
		Healthcheck: &Healthcheck{
			Test:     []string{"CMD", "mc", "ready", "local"},
			Interval: "5s",
			Timeout:  "3s",
			Retries:  10,
		},
		Restart:  "unless-stopped",
		Networks: []string{"piri-storage-net"},
	}
}

// ComposeFile represents a Docker Compose file.
type ComposeFile struct {
	Services map[string]ComposeService `yaml:"services"`
	Networks map[string]interface{}    `yaml:"networks,omitempty"`
	Volumes  map[string]interface{}    `yaml:"volumes,omitempty"`
}

// ComposeService represents a Docker Compose service definition.
type ComposeService struct {
	Image       string                         `yaml:"image,omitempty"`
	User        string                         `yaml:"user,omitempty"`
	Ports       []string                       `yaml:"ports,omitempty"`
	Volumes     []string                       `yaml:"volumes,omitempty"`
	Entrypoint  []string                       `yaml:"entrypoint,omitempty"`
	Command     []string                       `yaml:"command,omitempty"`
	Environment []string                       `yaml:"environment,omitempty"`
	DependsOn   map[string]DependsOnCondition  `yaml:"depends_on,omitempty"`
	Healthcheck *Healthcheck                   `yaml:"healthcheck,omitempty"`
	Restart     string                         `yaml:"restart,omitempty"`
	Networks    []string                       `yaml:"networks,omitempty"`
}

// DependsOnCondition specifies the condition for a depends_on entry.
type DependsOnCondition struct {
	Condition string `yaml:"condition"`
}

// Healthcheck represents a Docker Compose healthcheck.
type Healthcheck struct {
	Test        []string `yaml:"test"`
	Interval    string   `yaml:"interval,omitempty"`
	Timeout     string   `yaml:"timeout,omitempty"`
	Retries     int      `yaml:"retries,omitempty"`
	StartPeriod string   `yaml:"start_period,omitempty"`
}

func newComposeFile() *ComposeFile {
	return &ComposeFile{
		Services: make(map[string]ComposeService),
		Networks: make(map[string]interface{}),
		Volumes:  make(map[string]interface{}),
	}
}

func marshalCompose(compose *ComposeFile) ([]byte, error) {
	body, err := yaml.Marshal(compose)
	if err != nil {
		return nil, fmt.Errorf("marshal compose: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString(composeHeader)
	buf.Write(body)
	return buf.Bytes(), nil
}
